[Solutions] Local&Side Nav 컴포넌트와 제품 및 특징, 기능, 기대효과 컴포넌트 초안
ReOpenSG/ReOpenSG pull request #22
Opened 2023-12-08 01:48 UTC by ryudg

## 🔍️ 이 PR을 통해 해결하려는 문제가 무엇인가요?
> 어떤 기능을 구현한건지, 이슈 대응이라면 어떤 이슈인지 PR이 열리게 된 계기와 목적을 Reviewer 들이 쉽게 이해할 수 있도록 적어 주세요
일감 백로그 링크나 다이어그램, 피그마를 첨부해도 좋아요

- Solutions 페이지의 기능 및 레이아웃 (header, main, nav, footer 등 공통 section 을 제외) 을 구현하였습니다.

## ✨ 이 PR에서 핵심적으로 변경된 사항은 무엇일까요?
> 문제를 해결하면서 주요하게 변경된 사항들을 적어 주세요

- 테블릿, 데스크탑, 모바일 반응형 레이아웃 구현
- LNB 컴포넌트로 각각 솔루션들의 링크로 이동
- SNB 컴포넌트로 현재 페이지의 해당 섹션으로 이동
- 제품 및 특징, 기능, 기대효과를 더미 데이터(Json)을 이용해 불러와 리스트 렌더링

https://github.com/ReOpenSG/ReOpenSG/assets/103430498/9d2050f4-2019-4040-806c-54986d2e0a81

https://github.com/ReOpenSG/ReOpenSG/assets/103430498/4b81fa9a-4ac7-4e40-9887-f0bf79677694

## 🔖 핵심 변경 사항 외에 추가적으로 변경된 부분이 있나요?
> 없으면 "없음" 이라고 기재해 주세요

- 없음

## 🙏 Reviewer 분들이 이런 부분을 신경써서 봐 주시면 좋겠어요
> 개발 과정에서 다른 분들의 의견은 어떠한지 궁금했거나 크로스 체크가 필요하다고 느껴진 코드가 있다면 남겨주세요

- `<p className={styles.nav}>{prevLocation} &nbsp; &gt; &nbsp; {currentLocation}</p>` ➡️ ` > `
  - Solution Banner 상단의 현재 경로를 알려주는 텍스트를 `>`로 표기하는게 맞을지?!
![image](https://github.com/ReOpenSG/ReOpenSG/assets/103430498/c0364bd3-9340-42c7-b0b3-206c9baa523a)

## 🩺 이 PR에서 테스트 혹은 검증이 필요한 부분이 있을까요?
> 테스트가 필요한 항목이나 테스트 코드가 추가되었다면 함께 적어주세요
- 없음

### 📌 PR 진행 시 이러한 점들을 참고해 주세요

- Reviewer 분들은 코드 리뷰 시 좋은 코드의 방향을 제시하되, 코드 수정을 강제하지 말아 주세요.
- Reviewer 분들은 좋은 코드를 발견한 경우, 칭찬과 격려를 아끼지 말아 주세요.
- Review는 특수한 케이스가 아니면 Reviewer로 지정된 시점 기준으로 3일 이내에 진행해 주세요.
- Comment 작성 시 Prefix로 P1, P2, P3 를 적어 주시면 Assignee가 보다 명확하게 Comment에 대해 대응할 수 있어요
  - P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
  - P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
  - P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

#

---

## 📝 Assignee를 위한 CheckList

- [ ] To-Do Item

2023-12-08 04:45 UTC, dani-day requested changes
아래 파일에 의견 남겨두었습니다. 확인 부탁드립니다 😸
- LNB.jsx (P1 review)
- Solutions.jsx (P2 review)

2023-12-08 04:45 UTC, dani-day commented on src/components/Solutions/LNB.jsx
P1: LNB.jsx 만 다른 컴포넌트와 네이밍컨벤션이 다르게 적용된 것 같습니다. 컴포넌트 안에서도 Lnb 로 작성해주신 것 처럼 파일명도 동일하게 변경되면 좋을 것 같습니다 😄

2023-12-08 04:45 UTC, dani-day commented on src/views/Solutions.jsx
P2: Soultions.jsx 내에 작성되어있는 css 에서는 tailwindcss 에 spacing 설정을 해두었던 부분이 반영되지 않은 부분이 있어보입니다.

```html
<section className="b-[100px] w-full h-full desktop:px-[64px] tablet:px-[64px] px-[16px]">
```

open-gutter-mobile, open-gutter-desktop 등으로 변경되어야 추후 spacing 조절 시에 전체 적용되지 않을까 싶은데 이유가 있어 남겨두신 건가 싶어서 P2 로 의견 남기겠습니다.

2023-12-08 04:59 UTC, ryudg commented on src/components/Solutions/LNB.jsx
Rename으로 직접 파일명 변경 시 git이 파일명을 인식하지 못하는 문제가 있어서 `git mv LNB.jsx Lnb.jsx` 명령어로 변경 완료했습니다.

2023-12-08 05:05 UTC, ryudg commented on src/views/Solutions.jsx
`src/views/Solutions.jsx` Solutions 컴포넌트의 tailwindcss를 tailwind.config.js에 적용되어있는 css로 변경하였습니다.

https://github.com/ReOpenSG/ReOpenSG/blob/887e1602565155157bb0f204782b3b6333d5ced1/src/views/Solutions.jsx#L33-L47

2023-12-08 07:57 UTC, kelvin-chihyun approved these changes
확인했고, 큰 이상 없어 보입니다.

2023-12-08 07:57 UTC, kelvin-chihyun commented on src/routes/routes.jsx
P3: 주석처리하신 부분 삭제바랍니다!

2023-12-08 08:21 UTC, ingbinsee approved these changes
아래 파일에 의견 남겨두었습니다. 확인 부탁드립니다.

Lnb.jsx (P1 review)

2023-12-08 08:21 UTC, ingbinsee commented on src/components/Solutions/Lnb.jsx
P1: 뒤로가기 버튼 클릭 시 이전 solutions를 거쳐야만 원하는 페이지로 이동 가능합니다. 해당 부분 수정 요청합니다.

2023-12-08 12:57 UTC, ingbinsee requested changes
아래 파일에 의견 남겨두었습니다. 확인 부탁드립니다.

Lnb.jsx (P1 review)

2023-12-11 02:18 UTC, ryudg commented on src/components/Solutions/Lnb.jsx
해당 부분 이후 리팩토링 진행하면서 아이디어 나오는데로 수정하겠습니다.

2023-12-11 02:31 UTC, dani-day approved these changes
수정사항 확인했으며, 추가 리뷰드릴 내용은 없는 것 같습니다 👍

2023-12-11 02:36 UTC, ingbinsee approved these changes

2023-12-11 02:37 UTC, merged