[Contact] ContactTitle, Form, 개인정보 활용동의 컴포넌트 + emailJS 연결 초안
ReOpenSG/ReOpenSG pull request #42
Opened 2023-12-11 08:14 UTC by ingbinsee

## 🔍️ 이 PR을 통해 해결하려는 문제가 무엇인가요?

> 어떤 기능을 구현한건지, 이슈 대응이라면 어떤 이슈인지 PR이 열리게 된 계기와 목적을 Reviewer 들이 쉽게 이해할 수 있도록 적어 주세요
> 일감 백로그 링크나 다이어그램, 피그마를 첨부해도 좋아요

- Contact 페이지의 기능 및 레이아웃(header, main, nav, footer 등 공통 section 제외)을 구현하였습니다.

## ✨ 이 PR에서 핵심적으로 변경된 사항은 무엇일까요?

> 문제를 해결하면서 주요하게 변경된 사항들을 적어 주세요

- 분기점(모바일, 태블릿, 데스크탑)에 따른 반응형 레이아웃 구현
- Form 컴포넌트, 개인정보 활용동의 컴포넌트 제작
- emailJS 서비스 연결(설정된 이메일로 작성된 내용 발송)

https://github.com/ReOpenSG/ReOpenSG/assets/140426866/760a4971-d064-4610-b794-236d64e19544

## 🔖 핵심 변경 사항 외에 추가적으로 변경된 부분이 있나요?

> 없으면 "없음" 이라고 기재해 주세요

- 없음

## 🙏 Reviewer 분들이 이런 부분을 신경써서 봐 주시면 좋겠어요

> 개발 과정에서 다른 분들의 의견은 어떠한지 궁금했거나 크로스 체크가 필요하다고 느껴진 코드가 있다면 남겨주세요

- 없음

## 🩺 이 PR에서 테스트 혹은 검증이 필요한 부분이 있을까요?

> 테스트가 필요한 항목이나 테스트 코드가 추가되었다면 함께 적어주세요

- 없음

### 📌 PR 진행 시 이러한 점들을 참고해 주세요

- Reviewer 분들은 코드 리뷰 시 좋은 코드의 방향을 제시하되, 코드 수정을 강제하지 말아 주세요.
- Reviewer 분들은 좋은 코드를 발견한 경우, 칭찬과 격려를 아끼지 말아 주세요.
- Review는 특수한 케이스가 아니면 Reviewer로 지정된 시점 기준으로 3일 이내에 진행해 주세요.
- Comment 작성 시 Prefix로 P1, P2, P3 를 적어 주시면 Assignee가 보다 명확하게 Comment에 대해 대응할 수 있어요
  - P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
  - P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
  - P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

#

---

## 📝 Assignee를 위한 CheckList

- [ ] To-Do Item

2023-12-12 06:09 UTC, ryudg approved these changes

2023-12-12 06:09 UTC, ryudg commented on src/components/Contact/Agreement.jsx
> +import styles from '@/components/contact/Contact.module.css';
**P1**: `'@/components/contact/Contact.module.css'` 실제 경로명 `'@/components/Contact/Contact.module.css'`으로 변경해주세요

2023-12-12 06:09 UTC, ryudg commented on src/components/Contact/Agreement.jsx
> +            className={`peer ${styles.checkboxInput}`}
**P2** : 
기존 `onClick` prop보다 `onChange` prop으로 변경이 적절해 보입니다. (input이 **클릭**하는 이벤트 -> input의 값이 **변경**되는 이벤트)
이후, input 요소의 `checked` 속성에 `agreementStatus` 상태를 연결해 UI와 state간의 일치를 시켜주는게 좋을것 같습니다.
```jsx
<input
    // 생략...
    checked={agreementStatus}
    onChange={handleChangeCheck}
/>
```
이 경우 스크린 리더 및 보조 기술에서 `checked` 속성을 사용해 체크박스의 상태를 정확히 전달할 수 있습니다.
즉, `onClick` 이벤트만 사용하는 경우 스크린 리더와 같은 보조 기술은 실제로 체크박스의 상태를 감지하지 못할 수 있습니다.

2023-12-12 06:09 UTC, ryudg commented on src/components/Contact/Agreement.jsx
> +      <fieldset>
**P3**: 기존 중복되는 스타일 적용 코드를 개선하면 좋을것 같습니다.

```jsx
// src/components/Contact/Agreement.jsx

// ...생략
    <fieldset className={styles.agreementText}>
    <h3 className={styles.agreementTitle}>개인정보 활용동의</h3>
    <p className={`my-open-xl tablet:my-open-2xl desktop:my-open-2xl`}>
        OPENSG는 개인정보보호법 및 관련 법령에 의거 고객님들의 의견 접수와 관련한 성실한 답변을
        드리기 위해 필요한 최소한의 개인정보를 아래와 같이 수집, 이용하고자 합니다.
    </p>
    <ol className={styles.agreementOl}>
        <li>
        필수정보의 수집 목적 : 온라인 상담실을 통한 정보주체의 의견접수 및 문의에 대한 답변/안내
        </li>
        <li>
        필수 수집 항목 : 이름, 이메일 주소
        </li>
        <li>
        보유 및 이용기간 : 상담 신청 후 1년
        </li>
        <li>
        ※ 고객님께서는 본 동의를 거부하실 수 있으나 거부 시 필수정보의 수집 목적에 해당하는
        사항의 처리가 제한될 수 있습니다.
        </li>
    </ol>
    <div className={styles.checkboxWrapper}>
        <input
        type="checkbox"
        id="agreement"
        required
        onClick={handleChangeCheck}
        className={`peer ${styles.checkboxInput}`}
        />
        <label htmlFor="agreement" className={`pl-open-lg`}>
        (필수) 위 개인정보 수집 및 이용에 동의합니다.
        </label>
    </div>
    </fieldset>
// 생략...
```

```css
/* src/Contact/Contact.module.css */

/* 생략... */
    .agreementOl {
        @apply rounded-[20px] border -border--open-gray-300 px-open-lg tablet:px-open-xl desktop:px-open-xl py-open-xl tablet:py-open-2xl desktop:py-open-2xl;

        & li {
            @apply list-inside list-decimal;
        }
    }
/* 생략... */
```

2023-12-12 06:09 UTC, ryudg commented on src/components/Contact/ContactTitleInner.jsx
> +import styles from '@/components/contact/Contact.module.css';
**P1**: `@/components/contact/Contact.module.css` 실제 경로명 `@/components/Contact/Contact.module.css`으로 변경해주세요

2023-12-12 06:09 UTC, ryudg commented on src/components/Contact/ContactTitleSection.jsx
> +import styles from '@/components/contact/Contact.module.css';
**P1**: `@/components/contact/Contact.module.css` 실제 경로명 `@/components/Contact/Contact.module.css`으로 변경해주세요

2023-12-12 06:09 UTC, ryudg commented on src/components/Contact/Content.jsx
> +import styles from '@/components/contact/Contact.module.css';
**P1**: `@/components/contact/Contact.module.css` 실제 경로명 `@/components/Contact/Contact.module.css`으로 변경해주세요

2023-12-12 06:09 UTC, ryudg commented on src/components/Contact/InquiryInput.jsx
> +import styles from '@/components/contact/Contact.module.css';
**P1**: `@/components/contact/Contact.module.css` 실제 경로명 `@/components/Contact/Contact.module.css`으로 변경해주세요

2023-12-12 06:09 UTC, ryudg commented on src/components/Contact/InquiryType.jsx
> +import styles from '@/components/contact/Contact.module.css';
**P1**: `@/components/contact/Contact.module.css` 실제 경로명 `@/components/Contact/Contact.module.css`으로 변경해주세요

2023-12-12 06:09 UTC, ryudg commented on src/components/Contact/icons/ProductIcon.jsx
> +import styles from '@/components/contact/Contact.module.css';
**P1**: `@/components/contact/Contact.module.css` 실제 경로명 `@/components/Contact/Contact.module.css`으로 변경해주세요

2023-12-12 06:09 UTC, ryudg commented on src/components/Contact/PersonalInfo.jsx
> +import styles from '@/components/contact/Contact.module.css';
**P1**: `@/components/contact/Contact.module.css` 실제 경로명 `@/components/Contact/Contact.module.css`으로 변경해주세요

2023-12-12 06:09 UTC, ryudg commented on src/views/Contact.jsx
> +import Agreement from '@/components/contact/Agreement';
**P1**: `@/components/contact/Contact.module.css` 실제 경로명 `@/components/Contact/Contact.module.css`으로 변경해주세요

2023-12-12 06:09 UTC, ryudg commented on src/components/Contact/Agreement.jsx
> +      <ContactButton
**P3**: `ContactButton` 컴포넌트는 `form` 요소의 제출을 위한 버튼 컴포넌트도 확인 됩니다.
이 경우 "개인정보 활용동의"(`Agreement`) 컴포넌트 내부보다 `form` 요소 자체(`src/views/Contact`)에 구성되어있는게 가독성이 좋아보입니다.

2023-12-12 06:10 UTC, ryudg requested changes
요청 사항 확인하고 변경해주세요

2023-12-12 06:18 UTC, JuniorTunarr commented on src/views/Contact.jsx
> +    emailjs.sendForm('opensg', 'opensg', form.current, '6NuaSgBDx54b9MicI').then(
P1: API 관련 부분은 env에 변수로 보관해주세요!

2023-12-12 06:26 UTC, JuniorTunarr requested changes
P1: API 키는 보안 이슈가 있으니, 수정해주시길 바라겠습니다!

2023-12-12 06:26 UTC, JuniorTunarr commented on src/components/Contact/Contact.module.css
P2: Nesting 가능한 자식 태그는 부모 태그 아래에 두면, 가독성이 조금 더 좋아질 듯 합니다!

2023-12-12 06:57 UTC, ingbinsee commented on src/components/Contact/Agreement.jsx
> +import styles from '@/components/contact/Contact.module.css';
변경하였습니다.

2023-12-12 06:59 UTC, ingbinsee commented on src/components/Contact/Agreement.jsx
> +            className={`peer ${styles.checkboxInput}`}
디테일한 부분을 생각하지 못했습니다. 감사합니다.
반영하였습니다.

2023-12-12 07:21 UTC, ingbinsee commented on src/components/Contact/Agreement.jsx
> +      <fieldset>
스타일을 중복하여 사용하고 있음을 인지하지 못했네요. 감사합니다.
반영하였습니다.

2023-12-12 07:23 UTC, ingbinsee commented on src/components/Contact/icons/ProductIcon.jsx
> +import styles from '@/components/contact/Contact.module.css';
반영하였습니다.

2023-12-12 07:23 UTC, ingbinsee commented on src/components/Contact/ContactTitleInner.jsx
> +import styles from '@/components/contact/Contact.module.css';
변경하였습니다.

2023-12-12 07:24 UTC, ingbinsee commented on src/components/Contact/ContactTitleSection.jsx
> +import styles from '@/components/contact/Contact.module.css';
변경하였습니다.

2023-12-12 07:27 UTC, ingbinsee commented on src/components/Contact/Content.jsx
> +import styles from '@/components/contact/Contact.module.css';
변경하였습니다.

2023-12-12 07:28 UTC, ingbinsee commented on src/components/Contact/InquiryInput.jsx
> +import styles from '@/components/contact/Contact.module.css';
변경하였습니다.

2023-12-12 07:28 UTC, ingbinsee commented on src/components/Contact/InquiryType.jsx
> +import styles from '@/components/contact/Contact.module.css';
변경하였습니다.

2023-12-12 07:30 UTC, ingbinsee commented on src/components/Contact/PersonalInfo.jsx
> +import styles from '@/components/contact/Contact.module.css';
변경하였습니다.

2023-12-13 00:22 UTC, ingbinsee commented on src/views/Contact.jsx
> +import Agreement from '@/components/contact/Agreement';
변경하였습니다.

2023-12-13 00:45 UTC, ingbinsee commented on src/components/Contact/Agreement.jsx
> +      <ContactButton
ContactButton 컴포넌트를 &lt;form&gt;이 있는 ```src/views/Contact.jsx```로 이동하였습니다.

2023-12-13 01:34 UTC, ingbinsee commented on src/views/Contact.jsx
> +    emailjs.sendForm('opensg', 'opensg', form.current, '6NuaSgBDx54b9MicI').then(
API 관련 내용 env.local에 설정 후 불러오는 방식으로 수정하였습니다.

2023-12-13 01:49 UTC, ryudg approved these changes
수정 사항 모두 확인했습니다.

2023-12-13 01:56 UTC, ingbinsee commented on src/components/Contact/Contact.module.css
Nesting 가능한 자식 태그를 부모 태그 아래로 두었습니다.

2023-12-13 05:14 UTC, JuniorTunarr approved these changes
확인했습니다!

2023-12-13 05:14 UTC, merged