[Community] 커뮤니티 관련 컴포넌트 초안
ReOpenSG/ReOpenSG pull request #48
Opened 2023-12-12 05:55 UTC by JuniorTunarr

## 🔍️ 이 PR을 통해 해결하려는 문제가 무엇인가요?

> 어떤 기능을 구현한건지, 이슈 대응이라면 어떤 이슈인지 PR이 열리게 된 계기와 목적을 Reviewer 들이 쉽게 이해할 수 있도록 적어 주세요
> 일감 백로그 링크나 다이어그램, 피그마를 첨부해도 좋아요

- 커뮤니티 관련 페이지(Community / CommunityDetail / CommunityForm / Admin)의 기능 및 레이아웃을 구현하였습니다.
- 파이어베이스의 Fireauth, FireStore, Stroage 서비스를 활용해 더미데이터를 작성하여 CRUD 기능을 적용하였습니다.

## 1. Community(Read)
![커뮤니티1](https://github.com/ReOpenSG/ReOpenSG/assets/101504272/bf9a8944-f9aa-400b-aaac-2e53751e17a4)

## 2. CommunityDetail
![커뮤니티상세1](https://github.com/ReOpenSG/ReOpenSG/assets/101504272/d633f56c-58d3-4170-b73e-d99f25e0353f)

## 3-1. CommunityForm(Create)
![커뮤니티 글쓰기](https://github.com/ReOpenSG/ReOpenSG/assets/101504272/ae9f4bff-2269-4175-9f0b-94d887eebb23)

## 3-2. CommunityForm(Update)
![커뮤니티 수정하기](https://github.com/ReOpenSG/ReOpenSG/assets/101504272/31a95659-04d9-481e-8d57-29771ecf7794)

## 3-3. CommunityForm(Delete)
![커뮤니티 삭제하기](https://github.com/ReOpenSG/ReOpenSG/assets/101504272/a58f8375-78c8-48fa-97e2-788c008c400e)

## 4. Admin 
![어드민1](https://github.com/ReOpenSG/ReOpenSG/assets/101504272/3627aa21-09b3-4027-b0b5-d729068c8d1b)

## ✨ 이 PR에서 핵심적으로 변경된 사항은 무엇일까요?

> 문제를 해결하면서 주요하게 변경된 사항들을 적어 주세요

- 반응형을 적용하였습니다.
- CSS 모듈화하였습니다. (추후 페이지 컴포넌트도 적용 가능성 O)
- 컴포넌트를 분리하였습니다. (추후 추가 컴포넌트 분리 예정입니다.)

## 🔖 핵심 변경 사항 외에 추가적으로 변경된 부분이 있나요?

> 없으면 "없음" 이라고 기재해 주세요

-

## 🙏 Reviewer 분들이 이런 부분을 신경써서 봐 주시면 좋겠어요

> 개발 과정에서 다른 분들의 의견은 어떠한지 궁금했거나 크로스 체크가 필요하다고 느껴진 코드가 있다면 남겨주세요

-

## 🩺 이 PR에서 테스트 혹은 검증이 필요한 부분이 있을까요?

> 테스트가 필요한 항목이나 테스트 코드가 추가되었다면 함께 적어주세요

-

### 📌 PR 진행 시 이러한 점들을 참고해 주세요

- Reviewer 분들은 코드 리뷰 시 좋은 코드의 방향을 제시하되, 코드 수정을 강제하지 말아 주세요.
- Reviewer 분들은 좋은 코드를 발견한 경우, 칭찬과 격려를 아끼지 말아 주세요.
- Review는 특수한 케이스가 아니면 Reviewer로 지정된 시점 기준으로 3일 이내에 진행해 주세요.
- Comment 작성 시 Prefix로 P1, P2, P3 를 적어 주시면 Assignee가 보다 명확하게 Comment에 대해 대응할 수 있어요
  - P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
  - P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
  - P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

#

---

## 📝 Assignee를 위한 CheckList

- [ ] To-Do Item

2023-12-12 06:49 UTC, ingbinsee requested changes
아래 파일에 의견 남겨두었습니다. 확인 부탁드립니다.

- Admin.module.css (P2 review 2개)
- ButtonSection.jsx (P1 review)
- Community.jsx (P1 review 2개)

2023-12-12 06:49 UTC, ingbinsee commented on src/views/Community.jsx
> +import NoticeSection from '../components/Community/NoticeSection';
P1: 상대경로로 되어 있어 배포 환경에서 파일을 찾을 수 없다고 합니다. 절대경로로 변경 요청드립니다.

2023-12-12 06:49 UTC, ingbinsee commented on src/views/Community.jsx
> +import BannerSection from '../components/common/BannerSection';
P1: 폴더명이 소문자로 되어 있어 찾을 수 없다고 합니다. 대문자로 변경 요청드립니다.

2023-12-12 06:49 UTC, ingbinsee commented on src/components/Admin/Admin.module.css
P2: 모바일 버전에서 label의 스타일링이 깨집니다. 해당 부분 수정 요청드립니다.
![image](https://github.com/ReOpenSG/ReOpenSG/assets/140426866/2d5056e1-c7b1-474e-856d-5efe043650ee)

P2: 아이디와 비밀번호 form의 너비가 일정하지 않습니다. 해당 부분 수정 요청드립니다.
![image](https://github.com/ReOpenSG/ReOpenSG/assets/140426866/e5e54da4-30c5-4bef-8bcb-00ee8a467da4)

2023-12-12 06:49 UTC, ingbinsee commented on src/components/Community/ButtonSection.jsx
> +      </button>
P1: 취소하기 버튼 클릭 시 아래와 같은 오류가 발생합니다. 확인 후 수정 요청드립니다.
![image](https://github.com/ReOpenSG/ReOpenSG/assets/140426866/b66fd1f0-ee03-4f75-ad45-9d6c5e047d6e)

2023-12-12 08:18 UTC, JuniorTunarr commented on src/views/Community.jsx
> +import BannerSection from '../components/common/BannerSection';
변경했습니다.

2023-12-12 08:18 UTC, JuniorTunarr commented on src/views/Community.jsx
> +import NoticeSection from '../components/Community/NoticeSection';
변경했습니다.

2023-12-12 08:18 UTC, JuniorTunarr commented on src/components/Admin/Admin.module.css
변경했습니다.

2023-12-12 08:51 UTC, JuniorTunarr commented on src/components/Community/ButtonSection.jsx
> +      </button>
수정하였습니다.

2023-12-13 01:51 UTC, ryudg approved these changes
확인했습니다.
firebase, recoil 직접 사용해보고 아이디어 생각나면 공유해드리겠습니다.

2023-12-13 02:02 UTC, ingbinsee approved these changes
수정사항 확인했습니다.

2023-12-13 02:38 UTC, merged