[Header] Header 컴포넌트 내 메뉴 구조 및 링크 경로 수정
ReOpenSG/ReOpenSG pull request #84
Opened 2023-12-17 09:52 UTC by dani-day

## 🔍️ 이 PR을 통해 해결하려는 문제가 무엇인가요?

> 어떤 기능을 구현한건지, 이슈 대응이라면 어떤 이슈인지 PR이 열리게 된 계기와 목적을 Reviewer 들이 쉽게 이해할 수 있도록 적어 주세요
> 일감 백로그 링크나 다이어그램, 피그마를 첨부해도 좋아요

![스크린샷 2023-12-17 오후 6 24 15](https://github.com/ReOpenSG/ReOpenSG/assets/134567470/0e9ec6e7-a55f-482f-95c1-8cc762902802)

## ✨ 이 PR에서 핵심적으로 변경된 사항은 무엇일까요?

> 문제를 해결하면서 주요하게 변경된 사항들을 적어 주세요

- 기존 Smart Machine 메뉴의 구조를 일부 수정하고, Smart Machine, Smart Device 의 링크를 연결하였습니다.

## 🔖 핵심 변경 사항 외에 추가적으로 변경된 부분이 있나요?

> 없으면 "없음" 이라고 기재해 주세요

- 없음

## 🙏 Reviewer 분들이 이런 부분을 신경써서 봐 주시면 좋겠어요

> 개발 과정에서 다른 분들의 의견은 어떠한지 궁금했거나 크로스 체크가 필요하다고 느껴진 코드가 있다면 남겨주세요

- 없음

## 🩺 이 PR에서 테스트 혹은 검증이 필요한 부분이 있을까요?

> 테스트가 필요한 항목이나 테스트 코드가 추가되었다면 함께 적어주세요

- 없음

### 📌 PR 진행 시 이러한 점들을 참고해 주세요

- Reviewer 분들은 코드 리뷰 시 좋은 코드의 방향을 제시하되, 코드 수정을 강제하지 말아 주세요.
- Reviewer 분들은 좋은 코드를 발견한 경우, 칭찬과 격려를 아끼지 말아 주세요.
- Review는 특수한 케이스가 아니면 Reviewer로 지정된 시점 기준으로 3일 이내에 진행해 주세요.
- Comment 작성 시 Prefix로 P1, P2, P3 를 적어 주시면 Assignee가 보다 명확하게 Comment에 대해 대응할 수 있어요
  - P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
  - P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
  - P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

#

---

## 📝 Assignee를 위한 CheckList

- [ ] To-Do Item

2023-12-17 13:41 UTC, ingbinsee requested changes
아래에 의견 남겨두었습니다. 확인 부탁드립니다.
- Header.jsx (P1 review 3개)
- 모바일 Header의 링크는 수정이 되어 있지 않습니다. 해당 파일도 수정 후 PR 요청드립니다.
  + Industries에서 자동차 제외
  + machines 링크 수정
  + devices 링크 수정

2023-12-17 13:41 UTC, ingbinsee commented on src/layout/Header.jsx
P1: Open HSMS 링크 주소 수정 요청드립니다(154번째 줄).
```/solutions/Open HSMS``` > ```/solutions/HSMS```

2023-12-17 13:41 UTC, ingbinsee commented on src/layout/Header.jsx
>                      <MenuLink linkName="항만" linkAddress="/industries/semiconductor" />
P1: 2차전지 링크 주소 수정 요청드립니다.
```/industries/port``` > ```/industries/battery```

P1: 항만 링크 주소 수정 요청드립니다.
```/industries/semiconductor``` > ```/industries/port```

2023-12-18 00:37 UTC, kelvin-chihyun approved these changes
은빈님이 요청해주신 부분 외에 이의 없습니다.

2023-12-18 01:02 UTC, dani-day commented on src/layout/Header.jsx
주소 수정하였습니다!

2023-12-18 01:03 UTC, dani-day commented on src/layout/Header.jsx
>                      <MenuLink linkName="항만" linkAddress="/industries/semiconductor" />
링크 주소 수정 완료하였습니다 :) (Header 메뉴, Sitemap (데스크탑/모바일)

2023-12-18 01:12 UTC, ryudg approved these changes
이상 없습니다!!!

2023-12-18 01:24 UTC, ingbinsee approved these changes
확인했습니다.

2023-12-18 01:25 UTC, merged